### ISSUE TITLE
init.cpp

### ISSUE THREAD

**Issue by ddnut** [TrezarCoin/TrezarCoin#2]
Please remove lines 613 to 615 in init.cpp as it tosses errors and stops build on stock Ubuntu 16.04LTS

#ifdef USE_UPNP
    printf("Using miniUPnP Client v%s API v%d\n", MINIUPNPC_VERSION, MINIUPNPC_API_VERSION);
#endif

when removed I get no errors and build goes great. Thanks
TeG5nkcRmdJBYVke6eMyRb31qtAzCVQUwh

**Comment by ghostlander** [comment]
Don't build with USE_UPNP if you have no libminiupnpc with its headers installed. MINIUPNPC_VERSION and MINIUPNPC_API_VERSION are defined in miniupnpc/miniupnpc.h

**Comment by ddnut** [comment]
I did try with and without the USE_UPNP flag. I as well have libminiupnpc files installed. I did have the same issue on my pool with Orbit but no other coins on my neoscrypt machine.

**Comment by ghostlander** [comment]
What error do you get with it?

**Comment by ddnut** [comment]
`g++ -c -O2 -fomit-frame-pointer -fno-stack-protector -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -DBOOST_SPIRIT_THREADSAFE -I/root/TrezarCoin/src -I/root/TrezarCoin/src/obj -DUSE_UPNP=1 -DUSE_IPV6=1 -I/root/TrezarCoin/src/leveldb/include -I/root/TrezarCoin/src/leveldb/helpers -DHAVE_BUILD_INFO  -MMD -MF obj/init.d -o obj/init.o init.cpp
init.cpp: In function â€˜bool AppInit2()â€™:
init.cpp:614:51: error: â€˜MINIUPNPC_VERSIONâ€™ was not declared in this scope
     printf("Using miniUPnP Client v%s API v%d\n", MINIUPNPC_VERSION, MINIUPNPC_API_VERSION);
                                                   ^
init.cpp:614:70: error: â€˜MINIUPNPC_API_VERSIONâ€™ was not declared in this scope
     printf("Using miniUPnP Client v%s API v%d\n", MINIUPNPC_VERSION, MINIUPNPC_API_VERSION);
                                                                      ^
make: *** [obj/init.o] Error 1`

From fresh repo download same error

**Comment by ddnut** [comment]
`g++ -c -O2 -fomit-frame-pointer -fno-stack-protector -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -DBOOST_SPIRIT_THREADSAFE -I/root/TrezarCoin/src -I/root/TrezarCoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/root/TrezarCoin/src/leveldb/include -I/root/TrezarCoin/src/leveldb/helpers -DHAVE_BUILD_INFO  -MMD -MF obj/init.d -o obj/init.o init.cpp
init.cpp: In function â€˜bool AppInit2()â€™:
init.cpp:614:51: error: â€˜MINIUPNPC_VERSIONâ€™ was not declared in this scope
     printf("Using miniUPnP Client v%s API v%d\n", MINIUPNPC_VERSION, MINIUPNPC_API_VERSION);
                                                   ^
init.cpp:614:70: error: â€˜MINIUPNPC_API_VERSIONâ€™ was not declared in this scope
     printf("Using miniUPnP Client v%s API v%d\n", MINIUPNPC_VERSION, MINIUPNPC_API_VERSION);
                                                                      ^
make: *** [obj/init.o] Error 1`
0 flag on miniUPnP above is 1 flag

so you can`t enable or disable with command. if you leave no flag on miniUPnP it builds without it looks to be

**Comment by ghostlander** [comment]
init.cpp lines 20 to 22:
#ifdef USE_UPNP
#include <miniupnpc/miniupnpc.h>
#endif

You haven't included it apparently. Set USE_UPNP=- to exclude all uPnP code.

**Comment by ddnut** [comment]
and to include?

**Comment by ghostlander** [comment]
trezarcoin-qt.pro lines 80 to 82:

# use: qmake "USE_UPNP=1" ( enabled by default; default)
#  or: qmake "USE_UPNP=0" (disabled by default)
#  or: qmake "USE_UPNP=-" (not supported)

First two options compile the UPnP support in, the last one doesn't.

If you have libminiupnpc installed in /usr/local/lib and its headers in /usr/local/include, add -I/usr/local/include to make sure the compiler doesn't miss them.

**Comment by ddnut** [comment]
make -f makefile.unix USE_UPNP=1
`g++ -c -O2 -fomit-frame-pointer -fno-stack-protector -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -DBOOST_SPIRIT_THREADSAFE -I/root/TrezarCoin/src -I/root/TrezarCoin/src/obj -DUSE_UPNP=1 -DUSE_IPV6=1 -I/root/TrezarCoin/src/leveldb/include -I/root/TrezarCoin/src/leveldb/helpers -DHAVE_BUILD_INFO -MMD -MF obj/init.d -o obj/init.o init.cpp init.cpp: In function â€˜bool AppInit2()â€™: init.cpp:614:51: error: â€˜MINIUPNPC_VERSIONâ€™ was not declared in this scope printf("Using miniUPnP Client v%s API v%d\n", MINIUPNPC_VERSION, MINIUPNPC_API_VERSION); ^ init.cpp:614:70: error: â€˜MINIUPNPC_API_VERSIONâ€™ was not declared in this scope printf("Using miniUPnP Client v%s API v%d\n", MINIUPNPC_VERSION, MINIUPNPC_API_VERSION); ^ make: *** [obj/init.o] Error 1`

make -f makefile.unix USE_UPNP=0
`g++ -c -O2 -fomit-frame-pointer -fno-stack-protector -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -DBOOST_SPIRIT_THREADSAFE -I/root/TrezarCoin/src -I/root/TrezarCoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/root/TrezarCoin/src/leveldb/include -I/root/TrezarCoin/src/leveldb/helpers -DHAVE_BUILD_INFO -MMD -MF obj/init.d -o obj/init.o init.cpp init.cpp: In function â€˜bool AppInit2()â€™: init.cpp:614:51: error: â€˜MINIUPNPC_VERSIONâ€™ was not declared in this scope printf("Using miniUPnP Client v%s API v%d\n", MINIUPNPC_VERSION, MINIUPNPC_API_VERSION); ^ init.cpp:614:70: error: â€˜MINIUPNPC_API_VERSIONâ€™ was not declared in this scope printf("Using miniUPnP Client v%s API v%d\n", MINIUPNPC_VERSION, MINIUPNPC_API_VERSION); ^ make: *** [obj/init.o] Error 1`

make -f makefile.unix USE_UPNP= built just fine (notice no -)
Strange issue maybe something to do with the LXC Xenial Xerus image but other coins build fine except Orbit.  Any thoughts?

**Comment by ghostlander** [comment]
The same thing. Add -I/usr/local/include or where it is.
