### ISSUE TITLE
Can't compile on Ubuntu 18.04 - BIGNUM (ssl 1.1.0?)

### ISSUE THREAD

**Issue by Ur-Quan** [TrezarCoin/TrezarCoin#29]
Make says:

  CXX      primitives/libbitcoinconsensus_la-transaction.lo
In file included from primitives/transaction.cpp:8:0:
./key.h:238:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
                        ^~~~~~
In file included from /usr/include/openssl/bn.h:32:0,
                 from ./key.h:14,
                 from primitives/transaction.cpp:8:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
In file included from primitives/transaction.cpp:8:0:
./key.h: In constructor ‘CBigNum::CBigNum()’:
./key.h:243:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);

Googling leads to [this](https://github.com/bitshares/bitshares-core/issues/327), and seems that I'm on the same boat with #23 guy. Copypasting src/primitives and src/crypto wasn't successful. So - help pls!

**Comment by Bushstar** [comment]
Clean your build...

git clean -fdx

...then compile and use the depends folder.

https://github.com/TrezarCoin/TrezarCoin/tree/master/depends

**Comment by Ur-Quan** [comment]
`sudo apt-get install libssl1.0-dev`
did the trick
